[project]
name = "gentoogram-bot"
description = "Anti-spam bot for https://t.me/Gentoogram"
authors = [{ name = "Lee Watson", email = "me@lwatson.dev" }]
version = "0.10.0"
readme = "README.md"
license = { file = "LICENSE" }
requires-python = ">=3.14,<3.15"
dependencies = [
    "dynaconf>=3.2.10",
    "python-telegram-bot[webhooks]>=22.7",
    "sentry-sdk>=2.27.0",
]

[dependency-groups]
dev = [
    "pre-commit>=4.6.0",
    "pre-commit-hooks>=5.0.0",
    "ruff>=0.15.12",
    "shellcheck-py>=0.10.0.1",
    "yamllint>=1.37.1",
]

[tool.ruff]
force-exclude = true
extend-exclude = ["docker/data/", "docker/config/"]

[tool.ruff.format]
line-ending = "lf"

[tool.ruff.lint]
select = [
    "A",
    "ARG",
    "B",
    "BLE",
    "C4",
    "C90",
    "COM",
    "DTZ",
    "E",
    "ERA",
    "F",
    "FBT",
    "FIX",
    "FLY",
    "FURB",
    "G010",
    "G101",
    "G201",
    "G202",
    "I",
    "ICN",
    "INP",
    "ISC",
    "LOG",
    "N",
    "PERF",
    "PIE",
    "PL",
    "PT",
    "PTH",
    "PYI",
    "Q",
    "RET",
    "RSE",
    "RUF",
    "S",
    "SIM",
    "SLF",
    "SLOT",
    "T10",
    "T20",
    "TC",
    "TD",
    "TID",
    "TRY",
    "UP",
    "W",
    "YTT",
]

# ruff format compatibility
ignore = [
    "COM812",
    "COM819",
    "D206",
    "D300",
    "E111",
    "E114",
    "E117",
    "E501",
    "Q000",
    "Q001",
    "Q002",
    "Q003",
    "W191",
]
