---
name: "CI"

on: # yamllint disable-line rule:truthy
  push:
    branches:
      - "main"
  pull_request:

concurrency:
  group: "${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}"
  cancel-in-progress: true

jobs:
  lint:
    uses: "./.github/workflows/lint.yml"
  release:
    needs: "lint"
    uses: "./.github/workflows/release.yml"
